packages:
  - 001-hello-world
  - 002-lasagna
  - 003-annalyns-infiltration
  - 004-freelancer-rates
  - 005-poetry-club-door-policy
  - 006-elyses-enchantments
  - 007-vehicle-purchase
  - 008-bird-watcher
  - 009-mixed-juices
  - 010-lucky-numbers
  - 011-elyses-analytic-enchantments
  - 012-elyses-destructured-enchantments
  - 013-elyses-looping-enchantments
  - 014-amusement-park
  - 015-pizza-order
  - 016-coordinate-transformation
  - 017-fruit-picker
  - 018-translation-service
  - 019-high-score-board
  - 020-ozans-playlist
  - 021-lasagna-master
  - 022-factory-sensors
  - 023-elyses-transformative-enchantments
  - 024-custom-signs
  - 025-windowing-system
  - 026-regular-chatbot
  - 027-two-fer
  - 028-resistor-color
  - 029-resistor-color-duo
  - 030-gigasecond
  - 031-rna-transcription
  - 032-space-age
  - 033-pangram
  - 034-matrix
  - 035-bob
  - 036-book-store
  - 037-pascals-triangle
  - 038-linked-list
  - 039-grade-school
  - 040-list-ops
  - 041-robot-name
  - 042-simple-cipher
  - 043-wordy
  - 044-secret-handshake
  - 045-leap
  - 046-reverse-string
  - 047-collatz-conjecture
  - 048-triangle
  - 049-clock
  - 050-meetup
  - 051-etl
  - 052-hamming
  - 053-raindrops
  - 054-nucleotide-count
  - 055-scrabble-score
  - 056-allergies
  - 057-word-count
  - 058-bank-account
  - 059-difference-of-squares
  - 060-perfect-numbers
  - 061-complex-numbers
  - 062-luhn
  - 063-prime-factors
  - 064-grains
  - 065-pythagorean-triplet
  - 066-palindrome-products
  - 067-anagram
  - 068-acronym
  - 069-high-scores
  - 070-isogram
  - 071-matching-brackets
  - 072-phone-number
  - 073-scale-generator
  - 074-series
  - 075-largest-series-product
  - 076-transpose
  - 077-grep
  - 078-rectangles
  - 079-spiral-matrix
  - 080-ocr-numbers
  - 081-saddle-points
  - 082-forth
  - 083-food-chain
  - 084-house
  - 085-isbn-verifier
  - 086-pig-latin
  - 087-proverb
  - 088-twelve-days
  - 089-promises
  - 090-yacht
  - 091-beer-song
  - 092-resistor-color-trio
  - 093-dominoes
  - 094-say
  - 095-diamond
  - 096-rational-numbers
  - 097-sublist
  - 098-binary-search-tree
  - 099-custom-set
  - 100-binary-search
  - 101-circular-buffer
  - 102-simple-linked-list
  - 103-word-search
  - 104-variable-length-quantity
  - 105-two-bucket
  - 106-alphametics
  - 107-connect
  - 108-bowling
  - 109-strain
  - 110-flatten-array
  - 111-nth-prime
  - 112-sieve
  - 113-rotational-cipher
  - 114-diffie-hellman
  - 115-affine-cipher
  - 116-atbash-cipher
  - 117-crypto-square
  - 118-robot-simulator
  - 119-kindergarten-garden
  - 120-sum-of-multiples
  - 121-change
  - 122-protein-translation
  - 123-armstrong-numbers
  - 124-dnd-character
  - 125-run-length-encoding
  - 126-darts
  - 127-roman-numerals
  - 128-square-root
  - 129-all-your-base
  - 130-minesweeper
  - 131-queen-attack
  - 132-react
  - 133-zipper
  - 134-zebra-puzzle
  - 135-tournament
  - 136-rail-fence-cipher
  - 137-rest-api
  - 138-go-counting
  - 139-knapsack
  - 140-satellite
  - 141-poker
