packages:
  - 01-hello-world
  - 02-lasagna
  - 03-annalyns-infiltration
  - 04-freelancer-rates
  - 05-poetry-club-door-policy
  - 06-elyses-enchantments
  - 07-vehicle-purchase
  - 08-bird-watcher
  - 09-mixed-juices
  - 10-lucky-numbers
  - 11-elyses-analytic-enchantments
  - 12-elyses-destructured-enchantments
  - 13-elyses-looping-enchantments
  - 14-amusement-park
  - 15-pizza-order
  - 16-coordinate-transformation
  - 17-fruit-picker
  - 18-translation-service
  - 19-high-score-board
  - 20-ozans-playlist
  - 21-lasagna-master
  - 22-factory-sensors
  - 23-elyses-transformative-enchantments
  - 24-custom-signs
  - 25-windowing-system
  - 26-regular-chatbot
  - 27-two-fer
  - 28-resistor-color
  - 29-resistor-color-duo
  - 30-gigasecond
  - 31-rna-transcription
  - 32-space-age
  - 33-pangram
  - 34-matrix
  - 35-bob
  - 36-book-store
  - 37-pascals-triangle
  - 38-linked-list
  - 39-grade-school
  - 40-list-ops
  - 41-robot-name
  - 42-simple-cipher
  - 43-wordy
  - 44-secret-handshake
  - 45-leap
  - 46-reverse-string
  - 47-collatz-conjecture
  - 48-triangle
  - 49-clock
  - 50-meetup
  - 51-etl
  - 52-hamming
  - 53-raindrops
  - 54-nucleotide-count
  - 55-scrabble-score
  - 56-allergies
  - 57-word-count
  - 58-bank-account
  - 59-difference-of-squares
  - 60-perfect-numbers
  - 61-complex-numbers
  - 62-luhn
  - 63-prime-factors
  - 64-grains
  - 65-pythagorean-triplet
  - 66-palindrome-products
  - 67-anagram
  - 68-acronym
  - 69-high-scores
  - 70-isogram
  - 71-matching-brackets
  - 72-phone-number
  - 73-scale-generator
  - 74-series
  - 75-largest-series-product
  - 76-transpose
  - 77-grep
  - 78-rectangles
  - 79-spiral-matrix
  - 80-ocr-numbers
  - 81-saddle-points
  - 82-forth
  - 83-food-chain
  - 84-house
  - 85-isbn-verifier
  - 86-pig-latin
  - 87-proverb
  - 88-twelve-days
  - 89-promises
  - 90-yacht
  - 91-beer-song
  - 92-resistor-color-trio
  - 93-dominoes
  - 94-say
  - 95-diamond
  - 96-rational-numbers
  - 97-sublist
  - 98-binary-search-tree
  - 99-custom-set
  - 100-binary-search
  - 101-circular-buffer
  - 102-simple-linked-list
  - 103-word-search
  - 104-variable-length-quantity
  - 105-two-bucket
  - 106-alphametics
  - 107-connect
  - 108-bowling
  - 109-strain
  - 110-flatten-array
  - 111-nth-prime
  - 112-sieve
  - 113-rotational-cipher
  - 114-diffie-hellman
  - 115-affine-cipher
  - 116-atbash-cipher
  - 117-crypto-square
  - 118-robot-simulator
  - 119-kindergarten-garden
  - 120-sum-of-multiples
  - 121-change
  - 122-protein-translation
  - 123-armstrong-numbers
  - 124-dnd-character
  - 125-run-length-encoding
  - 126-darts
  - 127-roman-numerals
  - 128-square-root
  - 129-all-your-base
  - 130-minesweeper
  - 131-queen-attack
  - 132-react
  - 133-zipper
  - 134-zebra-puzzle
  - 135-tournament
  - 136-rail-fence-cipher
  - 137-rest-api
  - 138-go-counting
  - 139-knapsack
  - 140-satellite
  - 141-poker
